### ISSUE TITLE
Fixes to get this working on later versions of Blazor

### ISSUE THREAD

**Issue by tomRedox** [chrissainty/BlazorModal#1]
Hi @chrissainty - many thanks for posting this code, it's really useful.  As per the comments on the [Telerik blog post](https://www.telerik.com/blogs/creating-a-reusable-javascript-free-blazor-modal), the changes I made to get this working with .NET Core Preview 4 were:

- Change `BlazorComponent` to `ComponentBase` everywhere
- Namespaces changed a bit (let intellisense sort that out)
- Change .cshtml to .razor (and .cshtml.cs to .razor.cs)
- Change `@inherits ModalBase` to `@inherits BlazorModal.ModalBase` (might not be needed, think I hadn't changed the _Imports.razor file at that point)
- This is no longer needed: `@addTagHelper *, BlazorModal` (@addTagHelper no longer exists in Blazor) - use `@using BlazorModal` instead

Hopefully this will point anyone trying this code in the right direction in the meantime.

**Comment by chrissainty** [comment]
Hi @tomRedox,

Thanks so much for raising this. I don't get notified of comments on the Telerik posts so I hadn't seen them. I don't suppose you would be interested in raising a PR with the changes you made?

**Comment by chrissainty** [comment]
This has now been fixed by PR #2
