### ISSUE TITLE
The type or namespace 'App' couldn't be found...

### ISSUE THREAD

**Issue by MichaelJimma** [chrissainty/BlazorModal#11]
![Error](https://user-images.githubusercontent.com/22038220/84164553-a6b91e00-aa40-11ea-88b6-301117f6ce1f.png)

**Comment by chrissainty** [comment]
This repo is pretty old now and the structure of Blazor WebAssembly applications has changed quite significantly. This code was a precursor to [Blazored Modal](https://modal.blazored.com). I would check that out.
