### ISSUE TITLE
How to pass data to the inner component?

### ISSUE THREAD

**Issue by tomRedox** [chrissainty/BlazorModal#3]
Currently when using the ModalService we pass in the type of the component to be instantiated:

```
    ModalService.Show("Simple Form", typeof(SimpleForm));
```

That works fine where the inner component (`SimpleForm` in the code above) is a standalone component that contains all of its own logic, but what I'd like to be able to do is pass in parameters to the inner object.

What's led me to this is that I'm trying to use `Modal` to show a `DeletionConfirmation` dialog component I've written.  I need to either pass that dialog either the ID of the record to delete, or preferable a delegate method so it can then trigger the deletion of anything.  

What I think I need is a version of the `ModalService.Show` method that takes an instance of my `DeletionConfirmation` that I've already configured with the relevant call back delegate?  In pseudocode that would be something like:

    ModalService.Show("Simple Form", new DeletionConfirmation(myDeletionDelegate));

Would you have any idea how to go about doing that?  I think I'd need to :

 - Find a way to instantiate an instance of my `DeletionConfirmation` component in code
 - Changed the `ModalService` code to work with that instance instead of instantiating a new component from code?

**Comment by chrissainty** [comment]
Hi Tom,

If you check out Blazored Modal (https://github.com/Blazored/Modal) it's the "production version" of the code you've been looking at. With Blazored Modal, you can pass parameters to a modal as well as get results back from the modal. 

Best of all it's all packaged up for you ready to use on NuGet, no need to have to rewrite it all yourself.

**Comment by tomRedox** [comment]
Awesome, thanks Chris.  Some really useful looking other projects in [Blazored](https://github.com/Blazored) too, I'll be adding the [Toasts](https://github.com/Blazored/Toast) and [LocalStorage](https://github.com/Blazored/LocalStorage) into my project right away!

**Comment by chrissainty** [comment]
Great to hear, I'm working literally starting work on a Typeahead control today to add to Blazored as well.

**Comment by tomRedox** [comment]
Oh now that's very good news.. [quietly marks task to write a Typeahead as complete in DevOps] :D 

I'm not finding the putting extra hours in on Blazor a chore at the moment, it's simply the best new technology I've used in almost 20 years of coding!

**Comment by chrissainty** [comment]
Yeah I've been working with Blazor for over a year now, since before 0.1 and its just been a joy. Even back then when we could only use 2 events! lol

**Comment by tomRedox** [comment]
JavaScript.. get in the sea with you!!

I've just been looking at the Blazored.Modal version and getting up to speed on that.  It's great that it allows passing parameters through, but the way it's configured at the moment means that your inner component (`EditMovie` in the example) needs to be aware that it's being displayed in the Modal (it has to have the `ModalParameters` property and call `ModalService.Cancel()`).

In an ideal world I think the inner component would be unaware of where it's being displayed (e.g. so you could use it in a modal and on a standalone page)?  

I guess that would need:

 - The ability to instantiate the inner component in code first and wire up any properties it has - is that even possible in Blazor I wonder?
 - Adding events to the inner component that can then be handled externally and then wired up to the ModalService's show and cancel methods?

Did you look at anything like that at all?

**Comment by chrissainty** [comment]
You're correct the way it's built means the component in the modal needs to be aware it's in the modal. This was a deliberate design choice. 

I think one of the big sticking points, in my opinion, with components is the thought that they should be able to just be dropped in anywhere and work. I think in reality this is not what happens, within reason. 

The modal was built based on the requirements I have at work, my team is building a big multi-tenant application. We would never use a component that was in a modal elsewhere, it would be designed to work in the modal space. For example, a confirmation would never just be a random div somewhere on a page, it would always be in a modal. At least for us. 

I did explore making a modal where the inner component didn't have to be aware that it was in a modal but it got extremely complicated extremely quickly. And not just for me as a library author, the developer experience wasn't very good either. Hence the choice requiring components to know they are in a modal. 

However, saying all that. Just because the `EditMovie` component has a `CascadedParameter` defined doesn't mean it has to be populated. What I mean by this is you could add some logic into the `EditMovie` component where it operates differently depending on where its parameters come from. This would allow you to reuse it outside of the modal.

**Comment by tomRedox** [comment]
Thanks Chris, that all makes complete sense - I do agree about how (in)frequently components are actually reusable, nice an idea as it is.

What I was trying to achieve was a general purpose delete confirmation that I could pass delegates to, so I didn't have to write lots of very similar type-specific deletion confirmation components.  I can't do that with Blazor.Modal though, because I can't put a delegate in the ModalParameters collection.

I have a feeling that's probably not a very good design though from a single-responsibility point of view. 
 I think what I'll do instead is write a generic DeleteConfirmation component and then have type specific UI-less child deletion logic components that can be placed inside the DeleteConfirmation.  The general purpose DeleteConfirmation can be written to sit inside the Modal.  

I can then pass the object to be deleted to the Modal and the type-specific inner-most component can pick it up from the cascading parameters.  That should DRY out the HTML while still allowing the type-specificity needed for the delete.

**Comment by chrissainty** [comment]
That sounds like a good plan and a nice design. Let me know how you get on with it.

**Comment by tomRedox** [comment]
That worked nicely, the only change was to switch round the component order so that I have:
 `Modal` wraps `TypeSpecificNoUiComponent` wraps `DeletionConfimation`.

It has to be that way round of course, because I need to use the type-specific part in the call to: `ModalService.Show("Delete this specific thing", typeof(TypeSpecificNoUiComponent));`

The `TypeSpecificNoUiComponent` then unpacks the parameters and contains the business logic and sets the display properties in the `DeletionConfimation`.

The DeletionConfirmation ends up looking like this:

```
@using Microsoft.AspNetCore.Components

<div class="panel">
  <div class="panel-body">
    <p>@ModalDescription</p>
  </div>
  <div class="panel-footer">
    <div class="pull-right">
      <button type="button" class="btn btn-default" data-dismiss="modal" onclick="@CancelOnClick">Cancel</button>
      <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="@DeleteOnClick">@DeleteButtonText</button>
    </div>
  </div>
</div>


@functions {

  [Parameter]
  string ModalDescription { get; set; } = "Are you sure you want to delete this item?";

  [Parameter]
  string DeleteButtonText { get; set; } = "Delete";

  [Parameter]
  Action CancelOnClick { get; set; }

  [Parameter]
  Action DeleteOnClick { get; set; }
}
```

I belatedly clicked this solution is similar to what I'd of done with React/Redux.  

This approach has made the code a lot cleaner too.

**Comment by Aviio** [comment]
I managed to get around this particular problem by writing an extension for ModalParameters that uses the EventCallback Factory

//Extension
>   public static void AddConfirmCallback(this ModalParameters parameters, object receiver, Func<Task> callback)
        {
            parameters.Add("OnConfirm", EventCallback.Factory.Create(receiver, callback));
        }

Then I wired up this eventcallback to be invoked in my generic "confirm" modal
//Inside Generic "Confirm" modal
>private async void HandleContinue()
    {
        ModalResult result;
        isBusy = true;
        try
        {
            await OnConfirm.InvokeAsync(EventCallback.Empty);
            result = ModalResult.Ok<bool>(true);
        }
        catch (Exception ex)
        {
            result = ModalResult.Ok<bool>(false);
        }
        isBusy = false;
        Modal.Close(result);
    }

In the calling code that shows the modal
//Where the modal is shown from
>parameters.AddConfirmCallback(this, () =>
        {
            //logic to be invoked from within modal eg call to API
        });
Modal.Show<ConfirmModal>(title, parameters);
