### ISSUE TITLE
Preview 6 compatability

### ISSUE THREAD

**Issue by initMeta** [chrissainty/BlazorModal#6]
I am trying to follow along on this using preview 6 and there seems to be many compatibility issues. I have got it working in a fashion with preview 6 but instead of being styled like a modal it shows up to the left of the app window and doesn't seem to display correctly. I had to mix it a bunch with the preview 6 default app so that may be my issue. I should also say that I would like to get this functioning on a server side implementation if that's possible.

**Comment by chrissainty** [comment]
Hi @initMeta, this repo is a companion to the blog post which was obviously written at a point in time. Blazor is changing rapidly and there have been a few breaking changes. It's just not possible to keep every blog post and code sample updated. 

If you're interested in a ready made modal you can download [Blazored.Modal](https://github.com/Blazored/Modal). It was based off of this code but is much more feature rich and it's kept up to date with all the latest changes.
