### ISSUE TITLE
Update for Blazor event handler syntax

### ISSUE THREAD

**Issue by XeroPhane** [chrissainty/BlazorModal#7]
Change event handlers to be distinct from JavaScript event handlers, per latest (as of today) Blazor syntax.
(example issue here: https://stackoverflow.com/questions/56686732/blazor-does-not-refresh-ui-when-parameter-is-passed-with-onclick-function)

- Change onclick to @onclick
- Change bind to @bind
- etc.

IntelliSense should help for those elements the current syntax has adopted.

This fixed passing the modal form values to the alert output.

(Also awesome work with creating Blazor Modal!!)

Update:  the new syntax also replaces @functions with @code

**Comment by XeroPhane** [comment]
The text parsed incorrectly in my post.  The events should still be all lowercase such as "@ onclick" without the space between @ and [event]

**Comment by chrissainty** [comment]
Hi @XeroPhane, I’m going to be doing a big update of all my blog posts and code samples after preview 8 has landed as there are a lot of breaking changes coming. This code will get updated then.

**Comment by XeroPhane** [comment]
Awesome! Thank you!
